### ISSUE TITLE
problem when i try to deploy only on function

### ISSUE THREAD

**Issue by fzaffarana** [mooyoul/serverless-latest-layer-version#3]
When i try to deploy only one function: 

`serverless deploy --stage stage --region stage --function functionName`.

I get the this problem:

`validation error detected: Value '[arn:aws:lambda:region:amzAccountId:layer:worcket-handlers:latest, arn:aws:lambda:us-west-2:amzAccountId:layer:layerName:latest]' at 'layers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 140, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: (arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+)]`

It seems that it does not get the plugin for individual deploys.

**Comment by blaxk** [comment]
It seems to be fixed by adding hooks.

```
this.hooks = {
   'before:package:setupProviderConfiguration': this.beforeSetupProviderConfiguration.bind(this),
   'before:package:function:package': this.beforeSetupProviderConfiguration.bind(this)
};
```

**Comment by EliuX** [comment]
I am having that same problem

**Comment by mooyoul** [comment]
Hello there, This issue has been addressed from v2.0.0. Could you try again with new version of serverless-latest-layer-version plugin?

**Comment by EliuX** [comment]
Sure, I will do.

**Comment by mooyoul** [comment]
I checked this issue and i can confirm this issue still exists in latest version.

Individual function deployment strategy is different with default stack deployment strategy. Individual function deployment does not use CloudFormation and It just calls Lambda service APIs to update function. That's why this plugin never worked with individual function deployment.

Luckily, I have workaround for Individual function deployment and it will be fixed in next release.

**Comment by mooyoul** [comment]
I just published v2.1.0 which fixes this issue. Please try again with new version and let me know the results. Thanks for your patience!

**Comment by kanhaic** [comment]
I have tried to use this in version 2.1.2 and I am still getting an error. This is important for testing, deploying serverless project with a lot of functions takes at least 10 mins in my case.

```bash
serverless deploy -f import-job-handler
Running "serverless" from node_modules

Deploying function import-job-handler to stage prod (ap-south-1)

Code did not change. Function deployment skipped. (8s)
Environment: darwin, node 18.19.0, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
1 validation error detected: Value '[arn:aws:lambda:ap-south-1:*************:layer:utils:latest]' at 'layers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 2048, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+), Member must not be null]

1 deprecation found: run 'serverless doctor' for more details
```
